"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppBar from "./appBar";
import BreadCrumbs from "../components/breadcrumbs";
import { Provider } from "react-redux";
import store from "../store/store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata object is removed from export as it's not allowed in client components.
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = ["Homepages", "Login"];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <AppBar />
          <div className="bg-[#FAEBD7]">
            <BreadCrumbs Items={pages} />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}